### ISSUE TITLE
First click does not show animation

### ISSUE THREAD

**Issue by meierjan** [jaisonfdo/SearchViewSample#2]
Hey, 

I just read your code to see how you implemented it and I think I found a bug. If the activity is started and you click onto the search icon the animation is not executed. Instead the searchview is just displayed without an animation.

I think this is related to the fact that the toolbar is not visible initially and so it's not measured making width return 0.

**Comment by shinil7** [comment]
here's the [`solution`](https://github.com/jaisonfdo/SearchViewSample/pull/1)

**Comment by meierjan** [comment]
Thanks.
